# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: #表示什么时候执行这个脚本。 这里是当push代码到master时。 或者是pr合入请求到master时执行这个脚本
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:  # 执行的脚本内容就在jobs里。 还有build，也有deploy模块

  build:  # 这个名字是自定义的
    runs-on: ubuntu-latest  # runs-on表示当前build过程在ubuntu最新版里运行
    steps:
    - uses: actions/checkout@v3  # 这就是个中间件，把我们代码从github上拷贝下来的意思

    - name: Set up Go
      uses: actions/setup-go@v3  # 第二小步，设置代码的运行环境。这里是golang1.18
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...   # -v 当包编译的时候打印下包名    ./...是啥？  整条命令在本地也能跑，就是编译二进制

    - name: Test
      run: go test -v ./...
